# Generated by Django 4.1.6 on 2023-04-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_phone', models.CharField(max_length=10)),
                ('emp_about', models.TextField()),
                ('emp_position', models.CharField(choices=[('Manager', 'Manager'), ('Software Developer', 'software developer'), ('Project', 'pl')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapi.company')),
            ],
        ),
    ]
